// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function ApplyChanges(arg1) {
  return window['go']['main']['App']['ApplyChanges'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function ClearQueryHistory(arg1) {
  return window['go']['main']['App']['ClearQueryHistory'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectSaved(arg1) {
  return window['go']['main']['App']['ConnectSaved'](arg1);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecDML(arg1, arg2) {
  return window['go']['main']['App']['ExecDML'](arg1, arg2);
}

export function ExecuteIndexAlter(arg1, arg2) {
  return window['go']['main']['App']['ExecuteIndexAlter'](arg1, arg2);
}

export function ExecuteConstraintAlter(arg1, arg2) {
  return window['go']['main']['App']['ExecuteConstraintAlter'](arg1, arg2);
}

export function ExecutePartitionAlter(arg1, arg2) {
  return window['go']['main']['App']['ExecutePartitionAlter'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteTableAlter(arg1, arg2) {
  return window['go']['main']['App']['ExecuteTableAlter'](arg1, arg2);
}

export function ExportDump(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDump'](arg1, arg2, arg3);
}

export function FetchDatabases(arg1) {
  return window['go']['main']['App']['FetchDatabases'](arg1);
}

export function FetchEvents(arg1, arg2) {
  return window['go']['main']['App']['FetchEvents'](arg1, arg2);
}

export function FetchRoutines(arg1, arg2) {
  return window['go']['main']['App']['FetchRoutines'](arg1, arg2);
}

export function FetchTables(arg1, arg2) {
  return window['go']['main']['App']['FetchTables'](arg1, arg2);
}

export function FetchTriggers(arg1, arg2) {
  return window['go']['main']['App']['FetchTriggers'](arg1, arg2);
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetDataFilterHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDataFilterHistory'](arg1, arg2, arg3);
}

export function GetDatabasesFromCache(arg1) {
  return window['go']['main']['App']['GetDatabasesFromCache'](arg1);
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2);
}

export function GetSavedConnection(arg1) {
  return window['go']['main']['App']['GetSavedConnection'](arg1);
}

export function GetSyncState(arg1) {
  return window['go']['main']['App']['GetSyncState'](arg1);
}

export function GetTableAdvancedProperties(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableAdvancedProperties'](arg1, arg2, arg3);
}

export function GetTableDetailFromCache(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableDetailFromCache'](arg1, arg2, arg3);
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function GetTablesFromCache(arg1, arg2) {
  return window['go']['main']['App']['GetTablesFromCache'](arg1, arg2);
}

export function InitLocalDB() {
  return window['go']['main']['App']['InitLocalDB']();
}

export function KillQuery(arg1, arg2) {
  return window['go']['main']['App']['KillQuery'](arg1, arg2);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListSavedConnections() {
  return window['go']['main']['App']['ListSavedConnections']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function PreviewIndexAlter(arg1, arg2) {
  return window['go']['main']['App']['PreviewIndexAlter'](arg1, arg2);
}

export function PreviewConstraintAlter(arg1, arg2) {
  return window['go']['main']['App']['PreviewConstraintAlter'](arg1, arg2);
}

export function PreviewPartitionAlter(arg1, arg2) {
  return window['go']['main']['App']['PreviewPartitionAlter'](arg1, arg2);
}

export function PreviewTableAlter(arg1, arg2) {
  return window['go']['main']['App']['PreviewTableAlter'](arg1, arg2);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RunQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2, arg3);
}

export function RunQueryPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunQueryPage'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function SearchCompletions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCompletions'](arg1, arg2, arg3);
}

export function SetDataFilterHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetDataFilterHistory'](arg1, arg2, arg3, arg4);
}

export function SyncMetadata(arg1) {
  return window['go']['main']['App']['SyncMetadata'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TriggerSync(arg1) {
  return window['go']['main']['App']['TriggerSync'](arg1);
}
