// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {driver} from '../models';
import {database} from '../models';
import {main} from '../models';
import {store} from '../models';
import {cache} from '../models';

export function AddConnection(arg1:driver.ConnectionConfig):Promise<string>;

export function ApplyChanges(arg1:database.ChangeSet):Promise<database.ApplyResult>;

export function Connect(arg1:database.ConnectionConfig):Promise<main.ConnectResult>;

export function ConnectSaved(arg1:string):Promise<string>;

export function DeleteSavedConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecDML(arg1:string,arg2:string):Promise<database.ExecResult>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:number):Promise<database.ExecResult>;

export function ExecuteTableAlter(arg1:string,arg2:driver.SchemaChangeRequest):Promise<driver.SchemaChangeResult>;

export function FetchDatabases(arg1:string):Promise<Array<string>>;

export function FetchTables(arg1:string,arg2:string):Promise<Array<driver.TableInfo>>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetDBPath():Promise<string>;

export function GetDataFilterHistory(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetDatabasesFromCache(arg1:string):Promise<Array<string>>;

export function GetSavedConnection(arg1:string):Promise<store.SavedConnection>;

export function GetSyncState(arg1:string):Promise<cache.SyncStatus>;

export function GetTableAdvancedProperties(arg1:string,arg2:string,arg3:string):Promise<driver.AdvancedTableProperties>;

export function GetTableDetailFromCache(arg1:string,arg2:string,arg3:string):Promise<database.CachedTableEntry>;

export function GetTableSchema(arg1:string,arg2:string,arg3:string):Promise<cache.CachedTableSchema>;

export function GetTablesFromCache(arg1:string,arg2:string):Promise<Array<database.CachedTableEntry>>;

export function InitLocalDB():Promise<void>;

export function ListConnections():Promise<Array<main.ConnectionInfo>>;

export function ListSavedConnections():Promise<Array<store.SavedConnection>>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function PreviewTableAlter(arg1:string,arg2:driver.SchemaChangeRequest):Promise<driver.SchemaChangePreview>;

export function RemoveConnection(arg1:string):Promise<void>;

export function RunQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function SaveConnection(arg1:store.SavedConnection):Promise<void>;

export function SearchCompletions(arg1:string,arg2:string):Promise<Array<cache.CompletionItem>>;

export function SetDataFilterHistory(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SyncMetadata(arg1:string):Promise<void>;

export function TestConnection(arg1:store.SavedConnection):Promise<string>;

export function TriggerSync(arg1:string):Promise<void>;
